export { default as BOOT } from './Boot'
export { default as PRELOAD } from './Preload'
export { default as END } from './End'
export { default as IMAGE } from './Image'
export { default as TEXT } from './Text'
